from telnetlib import EC

from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time

from selenium.webdriver.support.wait import WebDriverWait


class landing:
    side_menu_bar = "//div[contains(@class,'sideMenuBar ng-star-inserted sm')]"
    hamburger_menu_right = "//img[@class='rightArrow']"
    hamburger_menu_left = "//img[@class='leftArrow']"
    kebab_menu = "(//img[@class='mat-menu-trigger dot'])[1]"
    bfsi_card = "//ion-label[contains(text(),'BFSI')]"
    drop_down_right = "(//img[@class='vectorDown'])[2]"
    search_bar = "(//input[contains(@placeholder,'Search')])[3]"
    plus_icon = "(//img[contains(@class,'addImg')])[3]"
    add_new_menu = "//ion-label[contains(normalize-space(),'Add a new')]"
    click_folder = "//ion-label[contains(normalize-space(),'Folder')]"
    folder_popup_title = "//div[@class='popupTitle']"
    save_button = '.add-btn.md.button.button-solid.ion-activatable.ion-focusable.hydrated'
    cancel_button = "//ion-button[normalize-space()='Cancel']"
    invalid_credentials_msg = "//div[@class='error-messages']"
    title_name = "//ion-input[contains(@formcontrolname,'title')]/input"
    description_text = "textarea"
    change_button = "//img[contains(@class,'change-logo')]"
    plan_radio_button = "//span[contains(@class,'mat-radio-inner-circle')][1]"
    plan_window = "//span[contains(text(),'Plan')]"
    click_vision = "//ion-label[contains(text(),'Vision')]"
    vision_popup_title = "//div[@class='popupTitle']"
    story_popup_title = "//div[@class='popupTitle']"
    click_story = "//ion-label[contains(text(),'Story')]"
    user_interface_popup_title = "//div[@class='popupTitle']"
    click_user_interface = "//ion-label[contains(text(),'User Interface')]"
    click_Specification = "//ion-label[contains(text(),'Specification')]"
    specification_popup_title = "//div[@class='popupTitle']"
    click_part = "//ion-label[contains(text(),'part')]"
    add_a_part_popup_title = "//div[@class='popupTitle']"
    button_add_a_new_part = "//button[contains(text(),'Add a New Part')]"
    title_add_a_new_part = "//label[contains(text(),'Add New Part')]"
    part_name_text_field = "//ion-input[contains(@formcontrolname,'name')]//input"
    part_about_text_field = "//ion-input[contains(@formcontrolname,'about')]//input"
    service_type_button = "//mat-select[@formcontrolname='serviceType']"
    front_end_dropdown = "//span[contains(text(),'Frontend')]"
    back_end_drop_down = "//span[contains(text(),'Backend')]"
    reuseable_part_select_type = "//div[contains(@id,'mat-select-value-3')]"
    reuseable_yes_option = "//span[contains(text(),'Yes (Re-usable)')]"
    reuseable_no_option = "//span[contains(text(),'No (App-specific)')]"
    part_repo_url_textfield = "//ion-input[contains(@formcontrolname,'repoUrl')]/child::input"
    pgm_plus_icon = "//img[@class='addHash']"
    add_language_tab = "//ion-label[contains(text(),'ADD Language')]"
    language_cancel_button = "(//ion-button[contains(text(),'Cancel')])[2]"
    add_language_text_field = "//input[contains(@placeholder,'Enter Language Name')]"
    add_svg_url_text_field = "//input[contains(@placeholder,'Enter SVG URL')]"
    add_language_cancel_button = ".md.button.button-outline.ion-activatable.ion-focusable.hydrated"
    add_language_add_button = "(//ion-button[contains(text(),'Add')])[2]"
    select_language_dropdown = "//ion-select[@formcontrolname='language']"
    select_language_options = "//div[contains(text(),'Angular')]"
    select_language_cancel_button = "//span[contains(text(),'Cancel')]"
    select_language_checkbox_language1 = "(//div[contains(@class,'alert-checkbox-icon sc-ion-alert-md')])[1]"
    select_language_checkbox_language2 = "(//div[contains(@class,'alert-checkbox-icon sc-ion-alert-md')])[2]"
    select_language_checkbox_language3 = "(//div[contains(@class,'alert-checkbox-icon sc-ion-alert-md')])[3]"
    select_language_checkbox_language4 = "(//div[contains(@class,'alert-checkbox-icon sc-ion-alert-md')])[4]"
    select_language_checkbox_language5 = "(//div[contains(@class,'alert-checkbox-icon sc-ion-alert-md')])[5]"
    select_language_ok_button = "//span[normalize-space()='OK']"
    add_button = "//ion-button[contains(text(),'Add')]"
    click_add_existing_part = "//button[contains(text(),'Add Existing Part')]"
    add_associated_part_title = "//ion-label[contains(text(),'Add Associated Part')]"
    project_select_part = "//input[@data-placeholder='select Part']"
    project_select_emas_card = "(//mat-option[contains(@role,'option')])[1]"
    project_select_skill_card = "(//mat-option[contains(@role,'option')])[2]"
    part_cancel_button = "//ion-button[contains(text(),'Cancel')]"
    part_add_button = "//ion-button[contains(text(),'Add')]"
    click_testing_folder = "(//img[contains(@src,'assets/icon/folder-blue.png')])[3]"
    dots_menu = "//img[@class='ellipseMargin']"
    dots_menu_options = "//div[contains(@class,'vision_more_options white-bg')]"
    click_documents = "//img[contains(@class,'visionOptionsImg padding-leftImg')]"
    documents_name_title = "//ion-label[contains(text(),'Documents')]"
    close_option = '.close_popover_icon.md.hydrated'
    click_pin = "//img[@src='assets/icon/pin.png']"
    click_people ="(//img[@class='visionOptionsImg'])[1]"
    people_name_title = "//ion-label[contains(text(),'People')]"
    click_tags = "(//img[@class='visionOptionsImg'])[2]"
    tags_name_title = "//ion-label[contains(text(),'Tags')]"
    click_linked_items = "(//img[@class='visionOptionsImg'])[3]"
    linked_items_tag_names = "//div[contains(text(),'Linked item')]"
    linked_items_close = "//ion-icon[contains(@name,'close')]"
    click_folder_part = "(//img[@class='visionOptionsImg'])[4]"
    folder_tile_name = "//div[contains(text(),'Folder')]"
    edit_pancel_button = "(//ion-col[@class='ng-star-inserted md hydrated'])[2]"
    upload_doc_text = "//ion-input[@formcontrolname='uploadTitle']//input"
    click_upload = "//label[contains(text(),'Upload')]"
    file_path = "//input[@type='file']"
    upload_doc_caret_dropdown = ".open-arrow.ng-star-inserted"
    upload_doc_caret_up_dropdown = ".open-arrow.ng-star-inserted"
    upload_doc_title = "//ion-label[starts-with(text(),'Upload Documents')]"
    upload_doc_cancel_button = "//button[contains(text(),'Cancel')]"
    upload_doc_save_button = "//button[contains(text(),'Save')]"
    click_add_prople_tab = "(//img[contains(@class,'visionOptionsImg')])[2]"
    add_people_title = "//ion-label[starts-with(text(),'Add people')]"
    add_people_drop_down = "//input[contains(@aria-invalid,'false')]"
    add_people_select_name_click = "//div[contains(@class,'addPeoplePopover white-bg')]"
    click_add_prople_check_box = "(//span[contains(@class,'mat-checkbox-inner-container')])[1]"
    click_add_prople_check_box_another = "(//span[contains(@class,'mat-checkbox-inner-container')])[3]"
    add_people_cancel_button = "//button[contains(text(),'Cancel')]"
    add_people_Save_button = "//button[contains(text(),'Save')]"
    click_add_prople_tags = "(//img[contains(@class,'visionOptionsImg')])[3]"
    add_people_tags_title = "//ion-label[contains(text(),'Add tags')]"
    click_linked_items_tab = "(//img[contains(@class,'visionOptionsImg')])[4]"
    linked_item_title = "//div[contains(text(),'Link item')]"
